### ISSUE TITLE
hotlink self expiring

### ISSUE THREAD

**Issue by TameOfGroans** [unsee-cc/backend#1]
I have used my own hosting for online image emails and cron deletion but I would prefer something more elegant perhaps unique views AND time window.

Is such within your plan for unsee [hotlink time views]

**Comment by Umkus** [comment]
It's already been implemented for some time now. For images that live until first view the time to live is just a couple of seconds. For those that live for a specific period of time - links live for that amount of time.

I used the nginx's [secure link module](http://nginx.org/en/docs/http/ngx_http_secure_link_module.html) to make it happen.
